name: Build and Push Docker Image to AWS ECR

on:
  push:
    branches: [main]
    paths:
      - "Docker/Dockerfile"
      - ".github/workflows/build.yml"

permissions: #(required for OIDC
  id-token: write 
  contents: read 
  
jobs:
  build:
    name: Build and push to ECR
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS Credentials (OIDC)
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_OIDC_ARN }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Log in to AWS ECR
      id: ecr-login
      uses: aws-actions/amazon-ecr-login@v2

    - name: Login to Docker Hardened Images (dhi.io)
      uses: docker/login-action@v3
      with:
        registry: dhi.io
        username: ${{ secrets.DHI_USERNAME }}
        password: ${{ secrets.DHI_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -f Docker/Dockerfile -t "$ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}" app
      env:
        ECR_REGISTRY: ${{ steps.ecr-login.outputs.registry }}
        ECR_REPOSITORY: gatus-app

    - name: Run Trivy scanner on Image
      uses: aquasecurity/trivy-action@0.33.1
      with:
        image-ref: "${{ steps.ecr-login.outputs.registry }}/gatus-app:${{ github.sha }}"
        format: table
        severity: CRITICAL,HIGH
        scanners: vuln
        ignore-unfixed: true
        exit-code: 1

    - name: Push Docker image to ECR
      run: |
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}
      env:
        ECR_REGISTRY: ${{ steps.ecr-login.outputs.registry }}
        ECR_REPOSITORY: gatus-app