name: Terraform Deploy

"on":
  push:
    branches: [ main ]
    paths:
      - "Terraform/**"
  workflow_dispatch:
permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: ${{ vars.INFRA_PATH }}
          soft_fail: true

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: terraform validate
        uses: dflook/terraform-validate@v2
        id: validate
        with:
          path: ${{ vars.INFRA_PATH }}

      - name: terraform fmt
        uses: dflook/terraform-fmt@v2
        with:
          path: ${{ vars.INFRA_PATH }}

      - name: terraform plan
        uses: dflook/terraform-plan@v2
        with:
          path: ${{ vars.INFRA_PATH }}   

      - name: terraform apply
        id: first-try
        uses: dflook/terraform-apply@v2
        continue-on-error: true
        with:
          path: ${{ vars.INFRA_PATH }}
          auto_approve: true
         

      - name: Unlock state if locked
        if: ${{ steps.first-try.outputs.failure-reason == 'state-locked' }}
        uses: dflook/terraform-unlock-state@v2
        with:
         path: ${{ vars.INFRA_PATH }}
         lock_id: ${{ fromJSON(steps.first-try.outputs.lock-info).ID }}


      - name: Retry terraform apply
        id: second-try 
        if: ${{ steps.first-try.outputs.failure-reason == 'state-locked' }}
        uses: dflook/terraform-apply@v2
        with:
          path: ${{ vars.INFRA_PATH }}
          auto_approve: true

  health-check:
    name: Post-Deploy Health Check
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Health check
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://${{ secrets.DOMAIN_NAME }}/health
          follow-redirect: true
          max-attempts: 20
          retry-delay: 15s

      - name: Success message
        run: echo "âœ… Health check passed for https://${{ secrets.DOMAIN_NAME }}/health"

      