name: Build and Push Docker Image to AWS ECR

on:
  push:
    branches: [main]
    paths:
      - "Docker/Dockerfile"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build push and deploy to ECS
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS Credentials (OIDC)
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_OIDC_ARN }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Log in to AWS ECR
      id: ecr-login
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build Docker image
      run: |
        docker build -f Docker/Dockerfile -t "$ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}" app
      env:
        ECR_REGISTRY: ${{ steps.ecr-login.outputs.registry }}
        ECR_REPOSITORY: gatus-repo

    - name: Run Trivy scanner on Image
      uses: aquasecurity/trivy-action@0.33.1
      with:
        image-ref: "${{ steps.ecr-login.outputs.registry }}/gatus-repo:${{ github.sha }}"
        format: table
        severity: CRITICAL,HIGH
        scanners: vuln
        ignore-unfixed: true
        exit-code: 1

    - name: Push Docker image to ECR
      run: |
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}
      env:
        ECR_REGISTRY: ${{ steps.ecr-login.outputs.registry }}
        ECR_REPOSITORY: gatus-repo

    - name: Render Amazon ECS task definition
      id: render-task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: ecs/task-definition.json  
        container-name: gatus-app                  
        image: "${{ steps.ecr-login.outputs.registry }}/gatus-repo:${{ github.sha }}"

    - name: Deploy to Amazon ECS service
      uses: aws-actions/amazon-ecs-deploy-task-definition@v2
      with:
        task-definition: ${{ steps.render-task-def.outputs.task-definition }}
        cluster: gatus-cluster                      
        service: gatus-service                      
        wait-for-service-stability: true