name: Terraform Deploy

"on":
  push:
    branches: [ main ]
    paths:
      - "infra/**"
  workflow_dispatch:
permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: infra
          soft_fail: true

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: terraform validate
        uses: dflook/terraform-validate@v2
        id: validate
        with:
          path: infra

      - name: terraform fmt
        uses: dflook/terraform-fmt@v2
        with:
          path: infra

      - name: terraform plan
        uses: dflook/terraform-plan@v2
        with:
          path: infra

      - name: Terraform Unlock
        uses: dflook/terraform-unlock-state@v2
        continue-on-error: true
        with:
           path: infra
           lock_id: ${{ secrets.LOCK_ID }}      

      - name: terraform apply
        uses: dflook/terraform-apply@v2
        with:
          path: infra
          auto_approve: true

  health-check:
    name: Post-Deploy Health Check
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Health check
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://${{ secrets.DOMAIN_NAME }}/health
          follow-redirect: true
          max-attempts: 20
          retry-delay: 15s

      - name: Success message
        run: echo "âœ… Health check passed for https://${{ secrets.DOMAIN_NAME }}/health"

      